# Generated by Django 5.1.1 on 2024-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_category_dishes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
